require('nvim-treesitter.configs').setup({
  ensure_installed = {
    'bash',
    'bibtex',
    'c',
    'c_sharp',
    'clojure',
    'cmake',
    'comment',
    'commonlisp',
    'cooklang',
    'cpp',
    'css',
    'dockerfile',
    'dot',
    'eex',
    'elixir',
    'elm',
    'erlang',
    'fish',
    'fortran',
    'gdscript',
    'gleam',
    'glsl',
    'go',
    'godot_resource',
    'gomod',
    'gowork',
    'graphql',
    'haskell',
    'heex',
    'html',
    'http',
    'java',
    'javascript',
    'jsdoc',
    'json',
    'kotlin',
    'latex',
    'llvm',
    'lua',
    'make',
    'norg',
    'ocaml',
    'ocaml_interface',
    'ocamllex',
    'perl',
    'php',
    'python',
    'query',
    'regex',
    'ruby',
    'rust',
    'scala',
    'scss',
    'surface',
    'svelte',
    'swift',
    'teal',
    'tlaplus',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'vue',
    'yaml',
    'zig',
    'help', -- experimental
    'markdown', -- experimental
    'markdown_inline', -- experimental
  },
  highlight = {
    enable = true,
  },
  playground = {
    enable = true,
  },
})
