#!/bin/sh

#< (git command) checkout the main branch (or argument), and fetch, prune, etc.

set -e

# https://coderwall.com/p/bt93ia/extend-git-with-custom-commands

source "$(git --exec-path)/git-sh-setup"

current_branch="$(git branch --show-current)"

git checkout "${1:-$(git main-branch)}"
git fetch --prune
git merge --ff-only

# remove branches whoese upstream is "[gone]"
git branch --verbose | grep "\[gone\]" | cut -d " " -f3 | xargs git branch -d

git checkout "$current_branch"
