#! /bin/sh

#< generate an epub of the current directory

if [[ $# != 1 ]]; then
  echo "Must give epub name"
  exit 1
fi

file="${1/.epub/}.epub"

rm -f $file

zip -X0 $file mimetype && \
  zip -Xur9D $file *
