#! /usr/bin/env bash


#< install postgis for the current asdf version

# https://github.com/smashedtoatoms/asdf-postgres/issues/5

set -e

if [[ $# != 1 ]]; then
  printf "Version not given, check https://postgis.net/source/\n"
  exit 1
fi

if [[ "$(uname -a)" =~ "Darwin" ]]; then
  projdir="--with-projdir=/usr/local/Cellar/proj/9.1.0"
fi

tmpdir=/tmp/postgis-install-"$@"
mkdir -p "$tmpdir/"

name=postgis-"$@"

wget -P "$tmpdir/" "https://download.osgeo.org/postgis/source/$name.tar.gz"
tar xvzf "$tmpdir/$name.tar.gz" -C "$tmpdir/"
pushd "$tmpdir/$name"

if [[ ! -a ./configure ]]; then
  ./autogen.sh
fi

eval ./configure "$(pg_config --configure)" "$projdir" --with-pgconfig="$(asdf which pg_config)"

make
make install

popd

rm -rf "$tmpdir/"


cat << EOF
Postgis has been installed, run the following in postgres to enable:

CREATE EXTENSION postgis;
CREATE EXTENSION postgis_raster;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION fuzzystrmatch;
CREATE EXTENSION address_standardizer_data_us;
CREATE EXTENSION postgis_tiger_geocoder;
EOF
