#! /bin/bash

#< download and unzip the latest elixir-ls release

read -p "Are you in the correct directory for downloaded and extraction? [yN]: " choice

if [[ ! $choice =~ ^[Yy] ]]; then
  exit 1
fi

rm -rf ./elixir-ls{,.zip} 2> /dev/null

curl -fLO https://github.com/elixir-lsp/elixir-ls/releases/latest/download/elixir-ls.zip
unzip elixir-ls.zip -d ./elixir-ls
chmod +x ./elixir-ls/language_server.sh
